"""add relationship in categories

Revision ID: 10ac9f0062cc
Revises: 7a8dc02f956e
Create Date: 2026-04-05 15:52:23.058403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10ac9f0062cc'
down_revision: Union[str, Sequence[str], None] = '7a8dc02f956e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('budgets', sa.Column('period_type', sa.String(length=20), nullable=False))
    op.add_column('budgets', sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('budgets', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('budgets', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('budgets', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('budgets', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('budgets', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_constraint(op.f('unique_budget'), 'budgets', type_='unique')
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.drop_constraint(op.f('budgets_category_id_fkey'), 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'year')
    op.drop_column('budgets', 'category_id')
    op.drop_column('budgets', 'amount')
    op.drop_column('budgets', 'month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('budgets_category_id_fkey'), 'budgets', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.create_unique_constraint(op.f('unique_budget'), 'budgets', ['user_id', 'category_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.alter_column('budgets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('budgets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('budgets', 'status')
    op.drop_column('budgets', 'is_recurring')
    op.drop_column('budgets', 'end_date')
    op.drop_column('budgets', 'start_date')
    op.drop_column('budgets', 'currency')
    op.drop_column('budgets', 'total_budget')
    op.drop_column('budgets', 'period_type')
    op.drop_column('budgets', 'name')
    # ### end Alembic commands ###
