"""add type to accounts table

Revision ID: 8b63dc1b03ad
Revises: 42cbdb989bb0
Create Date: 2026-03-28 16:28:15.292281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b63dc1b03ad'
down_revision: Union[str, Sequence[str], None] = '42cbdb989bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('type', sa.String(length=50), nullable=True))
    op.execute("UPDATE accounts SET type = 'cash' WHERE type IS NULL")
    op.alter_column('accounts', 'type', nullable=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'type')
    # ### end Alembic commands ###
