"""create new budget schema

Revision ID: aad2117a8cc4
Revises: db8ceb726375
Create Date: 2026-04-05 16:53:21.933662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad2117a8cc4'
down_revision: Union[str, Sequence[str], None] = 'db8ceb726375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('budget_categories', sa.Column('alert_percentage', sa.Integer(), nullable=False))
    op.add_column('budget_categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(op.f('unique_budget_category'), 'budget_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_budget_category'), 'budget_categories', ['budget_id', 'category_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('budget_categories', 'created_at')
    op.drop_column('budget_categories', 'alert_percentage')
    op.drop_column('budget_categories', 'allocated_amount')
    # ### end Alembic commands ###
